### PR TITLE
Improved UI

### PR DESCRIPTION
**Pull request by roadster31**
The module UI has been improved.
Translations are now working.

Thelia 2.1 required.

### CODE REVIEW

**Comment by lunika** [comment]
Why Thelia 2.1 is required ?

Thanks

**Comment by roadster31** [comment]
Because CreditAccount requires 2.1.

**Comment by lunika** [comment]
ok sorry I missed your PR on CreditAccount.

**Comment by lunika** [comment]
can you require credit account in your composer.json file ?

```
"thelia/creditaccount-module": "~1.0"
```

**Pull request closed without merging**
